project_id = "cgvdtcmchxkbnsdgbcvz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://127.0.0.1:54324"
enable_signup = true
minimum_password_length = 6
enable_anonymous_sign_ins = false
enable_confirmations = false

[auth.third_party.google]
enabled = false
client_id = ""
secret = ""

[db]
port = 54322

[edge_functions]
enabled = true
port = 54323

[functions.ask-jude]
verify_jwt = false

[functions.process-file-upload]
verify_jwt = false

[functions.generate-report]
verify_jwt = false