// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgvdtcmchxkbnsdgbcvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNndmR0Y21jaHhrYm5zZGdiY3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTk4NjUsImV4cCI6MjA3MDkzNTg2NX0.bGTEfgu5ry1-yiPp6ZMO_TtObHnoaHwKNssCGbZsJJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});